[2020-07-19 20:25:59,939] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: edmjnl_crawler6.schedule_edmjnl_email 2020-07-15T01:00:00+00:00 [queued]>
[2020-07-19 20:25:59,945] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: edmjnl_crawler6.schedule_edmjnl_email 2020-07-15T01:00:00+00:00 [queued]>
[2020-07-19 20:25:59,945] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-07-19 20:25:59,945] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-07-19 20:25:59,946] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-07-19 20:25:59,953] {taskinstance.py:901} INFO - Executing <Task(EmailOperator): schedule_edmjnl_email> on 2020-07-15T01:00:00+00:00
[2020-07-19 20:25:59,955] {standard_task_runner.py:54} INFO - Started process 29179 to run task
[2020-07-19 20:25:59,977] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'edmjnl_crawler6', 'schedule_edmjnl_email', '2020-07-15T01:00:00+00:00', '--job_id', '222', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags.py', '--cfg_path', '/tmp/tmp5kynql8o']
[2020-07-19 20:25:59,978] {standard_task_runner.py:78} INFO - Job 222: Subtask schedule_edmjnl_email
[2020-07-19 20:25:59,994] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: edmjnl_crawler6.schedule_edmjnl_email 2020-07-15T01:00:00+00:00 [running]> an
[2020-07-19 20:26:00,003] {taskinstance.py:1150} ERROR - [Errno 2] No such file or directory: 'home/antony/airflow/edmjnl/file.csv'
Traceback (most recent call last):
  File "/home/antony/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/antony/.local/lib/python3.8/site-packages/airflow/operators/email_operator.py", line 76, in execute
    send_email(self.to, self.subject, self.html_content,
  File "/home/antony/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 60, in send_email
    return backend(to, subject, html_content, files=files,
  File "/home/antony/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 99, in send_email_smtp
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'home/antony/airflow/edmjnl/file.csv'
[2020-07-19 20:26:00,004] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=edmjnl_crawler6, task_id=schedule_edmjnl_email, execution_date=20200715T010000, start_date=20200720T022559, end_date=20200720T022600
[2020-07-19 20:26:04,935] {local_task_job.py:102} INFO - Task exited with return code 1
